name: E2E

on:
  issue_comment:
    # types: [created]

jobs:
  e2e:
    name: E2E
    # if: contains(github.event.comment.body, '/e2e')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: test/1
      - name: e2e
        run: echo e2e is running
