name: E2E

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  e2e:
    name: E2E
    if: contains(github.event.comment.html_url, '/pull/') # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    steps:
      - name: E2E
        if: contains(github.event.comment.body, '/e2e') # check the comment if it contains the keywords
        run: |
          echo start e2e
      - name: Add E2E comment
        if: contains(github.event.comment.body, '/e2e') # check the comment if it contains the keywords
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.issue.pull_request)
            const baseURL = `https://github.com/${context.repo.owner}/${context.repo.repo}`
            const badgeURI = `${baseURL}/actions/workflows/${context.repo.owner}.yaml/badge.svg?branch=${encodeURI(context.ref)}`
            const workflowURL = `${baseURL}/actions/runs/${context.runId}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `E2E test is running -> [![E2E](${badgeURI})](${workflowURL})`
            })
      - name: Success
        run: |
          echo success
