name: CI HER End-to-End

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  e2e:
    if: contains(github.event.comment.html_url, '/pull/') # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    steps:
      - name: E2E
        if: contains(github.event.comment.body, '/e2e') # check the comment if it contains the keywords
        run: |
          echo start e2e
      - name: Add E2E comment
        if: contains(github.event.comment.body, '/e2e') # check the comment if it contains the keywords
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const encodedBranch = encodeURI("test/1")
            console.log(context)
            const baseURL = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/workflows/ci-e2e.yaml`
            const badgeURI = `${baseURL}/badge.svg?branch=${encodedBranch}`
            const workflowURL = `${baseURL}?query=branch%3A${encodedBranch}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀   [![E2E](${badgeURI})](${workflowURL})`
            })
      - name: Success
        run: |
          echo success
