name: E2E

on:
  check_run:
    types: [requested_action]

jobs:
  e2e:
    name: E2E
    # if: contains(github.event.comment.body, '/e2e')
    runs-on: ubuntu-latest
    steps:
      - name: e2e
        run: echo e2e is running
