name: E2E

on:
  issue_comment:
    # types: [created]

jobs:
  e2e:
    name: E2E
    # if: contains(github.event.comment.body, '/e2e')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 6c2f09d9295a7edadf667444e749b9c73aed2f1e
      - name: e2e
        run: echo e2e is running
