name: E2E

on:
  pull_request_review_comment:
    types: [created]

jobs:
  e2e:
    name: E2E
    if: contains(github.event.comment.body, '/e2e')
    runs-on: ubuntu-latest
    steps:
      - name: e2e
        run: echo e2e is running
